// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtBckDCj1n9gDOV0c_li08_6uaf5Y5xig',
    appId: '1:532671140616:web:407afd153f5ad4092112bd',
    messagingSenderId: '532671140616',
    projectId: 'kare-129da',
    authDomain: 'kare-129da.firebaseapp.com',
    storageBucket: 'kare-129da.appspot.com',
    measurementId: 'G-GVSH2MTVLB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRjSsCLtnBmsJ064X8jxUTQYAM0AETMpI',
    appId: '1:532671140616:android:e3557e568b6c86de2112bd',
    messagingSenderId: '532671140616',
    projectId: 'kare-129da',
    storageBucket: 'kare-129da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-_zgVSGiGN2tnKH155-TRtwtuiaqMm7A',
    appId: '1:532671140616:ios:60e079ff2329ad992112bd',
    messagingSenderId: '532671140616',
    projectId: 'kare-129da',
    storageBucket: 'kare-129da.appspot.com',
    iosBundleId: 'com.example.secureKare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-_zgVSGiGN2tnKH155-TRtwtuiaqMm7A',
    appId: '1:532671140616:ios:60e079ff2329ad992112bd',
    messagingSenderId: '532671140616',
    projectId: 'kare-129da',
    storageBucket: 'kare-129da.appspot.com',
    iosBundleId: 'com.example.secureKare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtBckDCj1n9gDOV0c_li08_6uaf5Y5xig',
    appId: '1:532671140616:web:fdb665eec44b50de2112bd',
    messagingSenderId: '532671140616',
    projectId: 'kare-129da',
    authDomain: 'kare-129da.firebaseapp.com',
    storageBucket: 'kare-129da.appspot.com',
    measurementId: 'G-S8KRGX4LQ7',
  );
}
